import time

from util import log

log.init("/var/log/clauto")
while 1:
    time.sleep(1)

    log.level_set("CRT")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")

    log.level_set("CFG")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")

    log.level_set("ERR")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")

    log.level_set("WRN")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")

    log.level_set("INF")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")

    log.level_set("DBG")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")

    log.level_set("VRB")
    log.critical("This message is critical")
    log.config("This message is configgey")
    log.error("This message is errorey")
    log.warning("This message is a warning")
    log.info("This message is informative")
    log.debug("This message is debuggey")
    log.verbose("This message is verbose")
